### ISSUE TITLE
randomizedtesting suffers from numerous maven issues

### ISSUE THREAD

**Issue by rmuir** [randomizedtesting/randomizedtesting#199]
I've been wondering for a while why i can't get tests to pass (which would be useful, e.g. to try to submit some improvements)... i finally dug in.
- randomizedtesting gets hit with https://issues.apache.org/jira/browse/MNG-5346. I was using maven 3.2.1. Maybe enforcer plugin can help prevent confusion instead of:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.4:descriptor (default-descriptor) on project junit4-maven-plugin: Error extracting plugin descriptor: 'No mojo definitions were found for plugin: com.carrotsearch.randomizedtesting:junit4-maven-plugin.' -> [Help 1]
```
- `mvn test` doesn't seem to work (I tried several maven versions). I think its some issue with the shade plugin and multi-module builds. Looks like this:

```
[ERROR] Failed to execute goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.2.0-SNAPSHOT:junit4 (junit4-tests) on project randomizedtesting-examples: The following error occurred while executing this line:
[ERROR] /home/rmuir/workspace/randomizedtesting/junit4-ant/target/classes/com/carrotsearch/junit4/antlib.xml:4: taskdef A class needed by class com.carrotsearch.ant.tasks.junit4.JUnit4 cannot be found: org/objectweb/asm/ClassVisitor
[ERROR] using the classloader AntClassLoader[/home/rmuir/workspace/randomizedtesting/junit4-ant/target/classes:/home/rmuir/.m2/repository/junit/junit/4.10/junit-4.10.jar:/home/rmuir/.m2/repository/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar]: org.objectweb.asm.ClassVisitor
```

A workaround for me is to not use `mvn test`, and to use `mvn package`

**Comment by dweiss** [comment]
(1) didn't know about the issue, but yes, an enforcer rule can be added.
(2) this is in general a problem with maven - a {{mvn test}} never reaches those build stages that actually build the final distribution (obfuscate, repackage, etc.). You can {{mvn install}} the package first, then run {{mvn test}}, but it'd be testing what you have installed in your local repo, not the current code. I don't know how to solve this with maven, it seems it's just not a good fit for builds which do bytecode manipulation during packaging. @rjernst is working on a gradle plugin, perhaps he can convert the build to gradle so that build order dependencies actually make sense... :)

**Comment by dweiss** [comment]
bq. A workaround for me is to not use mvn test, and to use mvn package

This isn't a workaround, it's "the maven way"...

**Comment by rmuir** [comment]
Well, i am not sure its the maven way, I think something is wrong if you have module A and module B, and B.test depends on A.package, that is just my opinion. But i agree, maven is frustrating.

**Comment by dweiss** [comment]
If you can constructively point me at a solution in which module A is repackaged and this is a form in which it should be tested (because repackaging and trimming can break things) and B just runs with "mvn test" then I'd love to change it. I haven't found a way to achieve it and I've tried many times. It'd require inter-module dependency so that B.test requires A.package, there is no such thing in maven.

**Comment by rmuir** [comment]
If module A's tests depends on module B's *package* then those are integration tests, e.g. `mvn verify`. If run from the integration test phase (which happens after package), then things will always work.

And RR works nicely with integration tests now so I think it could be fixed to work that way?

**Comment by uschindler** [comment]
You could simply bind the Mojo to the verify phase. It's part of pom, just change the phase setting. By default its bound to test.

**Comment by dweiss** [comment]
Nothing is simple or straightforward with Maven. There is a corner case for every workaround... Trust me, I've been there, I hate it.

I know @rjernst is working on getting ES running with Gradle -- once he solves all the hard issues, I'm planning to migrate over to gradle too (and steal all that secret sauces he's been brewing).

**Comment by uschindler** [comment]
And forbiddenapis also works with Gradle now :)
