### ISSUE TITLE
Feature request: Provide "skipNonTests" attribute as known from ANT 1.9 JUnit task

### ISSUE THREAD

**Issue by dw-fmueller** [randomizedtesting/randomizedtesting#230]
ANT 1.9 JUnit task provides a nice attribute called "skipNonTests". This attribute configures the JUnit task to "Do not pass any classes that do not contain JUnit tests to the test runner."
See https://ant.apache.org/manual/Tasks/junit.html

When using randomizedtesting you need to filter out classes w/o tests before providing them to randomizedtesting. Filtering is usually done using ANT pattern sets which rely on a certain naming scheme of your test classes.

Naming schemes are hard to enforce in a team with lots of people contributing to your code base.

It would be very helpful to have the same capability in randomizedtesting what ANT provides you with "skipNonTests".

**Comment by dweiss** [comment]
This is intentional, not an oversight. When you're passing class names that are NOT tests, you need some kind of heuristic to verify whether something is a test or not. Quoting this attribute from JUnit:

"Tests are identified by looking for the @Test annotation on any methods in concrete classes that don't extend junit.framework.TestCase, or for public/protected methods with names starting with 'test' in concrete classes that extend junit.framework.TestCase. Classes marked with the JUnit4 org.junit.runner.RunWith or org.junit.runner.Suite.SuiteClasses annotations are also passed to JUnit for execution, as is any class with a public/protected no-argument suite method."

Note that these tests will require parsing the class as a bytecode or loading it from memory. To me neither is attractive -- parsing will repeatedly increase execution time and loading into memory may have other side effects (static class initializers being executed, for example).

So while technically doable, I don't think I buy the argument that it is actually a good practice to follow...

**Comment by dw-fmueller** [comment]
I agree on the fact about the technical impact of that flag.
However, from a business and QA perspective, a test case that does not get executed in your test automation is a loss of test coverage and eventually a loss of money if a bug does not get discovered.
If you have thousands of tests being executed per test run it happens quite quickly that you overlook that a test does not get executed.
While, in theory, it is good practice to follow a naming scheme for your test classes, in reality it is harder to enforce this policy.

I would vote for a "skipNonTests" attribute with default = “off” and a warning in the ANT doc  about its impact.

Best
Frank

**Comment by dweiss** [comment]
Feel free to provide a patch if this is your desire. I will only accept it if it uses bytecode parsing though, no loading of arbitrary classes just to inspect them via reflection.

Also, don't get me wrong, but if your organization is so hard to control then I'd really implement such checks as a separate integration-time plugin in your build system (verify that all test classes are named appropriately). This would be a better solution because it'd also clean up your code rather then just yielding to the bad habit of naming tests whatever you like...
