### ISSUE TITLE
Test Name is null for Classes Marked as Ignored

### ISSUE THREAD

**Issue by szaluk** [randomizedtesting/randomizedtesting#274]
I am seeing strange behavior for classes that are marked with `@Ignore` and how the tests in those classes are processed.  I have an external RunListener that processes the statuses of the tests.  The issue I am seeing is the RunListener is being invoked once regardless of how many tests are in it but the test name is coming up as null like so:

`com.packagename.TestClassName.null`

You can also see this behavior in the following test:

https://github.com/randomizedtesting/randomizedtesting/blob/master/randomized-runner/src/test/java/com/carrotsearch/randomizedtesting/contracts/TestClassLevelIgnore.java

The output from that test is the following:

```
build	20-Nov-2018 11:42:55	[INFO] Running com.carrotsearch.randomizedtesting.contracts.TestClassLevelIgnore
build	20-Nov-2018 11:42:55	Run started.
build	20-Nov-2018 11:42:55	Ignored : null
build	20-Nov-2018 11:42:55	Run finished: run=0, ignored=1, failures=0, assumptions=0
```

In that output you can see the test name is being displayed as null.

is this intended behavior of the runner?

**Comment by dweiss** [comment]
Hmm... no, this looks strange. I'll take a look at it tomorrow.

**Comment by szaluk** [comment]
Thanks!

**Comment by dweiss** [comment]
This is actually correct behavior. If you place an Ignore annotation on a class, the entire class is ignored (no hooks or rules are executed, no methods are evaluated). That's why PrintEventListener emits 'null' from a call to ``description.getMethodName()``: there is no method that was ignored, it was the entire class.

This behavior simulates original JUnit (if you remove ``extends RandomizedTest`` from Nested class in TestClassLevelIgnore, it'll show you exactly the same thing.

This is also the reason why RunListenerEmitter in the ANT runner has such complex logic to determine the cause for ignored call, see here:

https://github.com/randomizedtesting/randomizedtesting/blob/b022f52df8f66f05c364dbade26f6912baa758f0/junit4-ant/src/main/java/com/carrotsearch/ant/tasks/junit4/slave/RunListenerEmitter.java#L75-L108

I'll correct PrintEventListener, but in general if you use a custom listener this is what you'll get.
