### ISSUE TITLE
Runner throws `NoTestsRemainException` when method filter is supplied

### ISSUE THREAD

**Issue by mark-vieira** [randomizedtesting/randomizedtesting#283]
Release 2.7.5 introduced a change wherein if a method filter is supplied via the `prefix.method` system property a `NoTestsRemainException` even if there are other test suites for which the method filter _does_ match. This seems to be because we apply method filters before class filters, so even if a later class will match our filter we fail all other test suites even if they are also filtered out vi a `prefix.class` filter.

This current behavior effectively makes it impossible to use method filters for any test execution which includes more than a single test suite. The expected behavior should be that class filters by applied _first_ and we only throw the `NoTestsRemainException` if none of the remaining classes match the supplied method filter.

**Comment by dweiss** [comment]
Would you be able to provide a patch Mark? I will not be able to look into
this until the end of the week.

**Comment by dweiss** [comment]
Hmm... I don't think this is a bug. The current implementation follows the specification of Filterable:
https://junit.org/junit4/javadoc/latest/org/junit/runner/manipulation/Filterable.html

This change has been introduced because IDEs rely on this feature. The test "launcher" should handle this (this is logically above RandomizedRunner).

> This seems to be because we apply method filters before class filters, so even if a later class will match our filter we fail all other test suites even if they are also filtered out vi a prefix.class filter.

What's the "we" here? ES switched to gradle's test task, right? This task should handle those exceptions from Filterable interface; if it doesn't then it's a bug in gradle.

**Comment by dweiss** [comment]
I've taken a look. Gradle assumes the class instance is always successfully created, then follows on to filtering. RR filters eagerly. 

https://github.com/gradle/gradle/blob/2d7f977d9f34e55419396cc24318d2c9a7e274ea/subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractMultiTestRunner.java#L136-L167

I'll provide a patch.

**Comment by dweiss** [comment]
Should be fine in 2.7.7, will release shortly. Thanks for the tip.

**Comment by mark-vieira** [comment]
> Should be fine in 2.7.7, will release shortly. Thanks for the tip.

Awesome. Thanks, Dawid!
