### ISSUE TITLE
Project does not build on Java 14

### ISSUE THREAD

**Issue by odaira** [randomizedtesting/randomizedtesting#288]
```
$ java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7-Ubuntu-1ubuntu1)
OpenJDK 64-Bit Server VM (build 14.0.1+7-Ubuntu-1ubuntu1, mixed mode, sharing)
$ mvn -X package
...
org.apache.maven.enforcer.rule.api.EnforcerRuleException: IMPORTANT! You must set proguard.rt.jar or proguard.java.home manually for obfuscation.
Some required files are missing:
/usr/lib/jvm/java-14-openjdk-amd64/lib/rt.jar
...
```
rt.jar no longer exists in Java 9 or later.  Any tips to build the project with a recent JDK?

**Comment by dweiss** [comment]
You need to compile with an older JDK. Technically it would be possible to upgrade proguard - then it'd consume module instead of runtime jar, but since we want backward compatibility with older JDKs anyway, it's safer to compile with against the oldest one supported.

Do you have to compile from sources? What's your goal - perhaps the binaries would suffice?

**Comment by odaira** [comment]
I was just curious about the project's source and binary support for a recent JDK.  I don't need to compile from sources, and my actual issue is #289.  Thanks for your response!
