### ISSUE TITLE
Upgrading dependent version of org.ow2.asm to support Java 13 or later

### ISSUE THREAD

**Issue by odaira** [randomizedtesting/randomizedtesting#289]
The current dependent version of 6.2.1 does not support Java 13 or later.
https://gitlab.ow2.org/asm/asm/-/blob/ASM_6_2_1/asm/src/main/java/org/objectweb/asm/ClassReader.java#L176

My project is using randomizedtesting but cannot test with Java 13 due to this problem.  Any plan to upgrade the dependent version?

**Comment by dweiss** [comment]
Ok, let me take a look.

**Comment by dweiss** [comment]
To be clear: you can use randomizedtesting just fine with Java 13, 14 and any newer one. It is the ant runner that will have problems with newer JDKs (because it parses java classes looking for method signatures). You can use randomized testing with any test runner though (built-in into your build system - be it gradle, maven or ant).

**Comment by dweiss** [comment]
I updated asm to 8.0.1, hope it'll help. If you're using gradle or maven then I'd just use the test runners available there. Thank you for letting me know though.

**Comment by dweiss** [comment]
I've just pushed 2.7.8 to maven central with this fix applied.

**Comment by odaira** [comment]
thank you!

**Comment by dweiss** [comment]
You're welcome :)
